In [1]:
import numpy as np

a = np.array([1,2,4,5]) 
b = np.array([23, 4, 6, 7])

print(np.shape(a))
print(np.shape(b))

(4,)
(4,)


In [2]:
print(a+b)
print(a-b)
print(a*b)

[24  6 10 12]
[-22  -2  -2  -2]
[23  8 24 35]


In [3]:
c = np.arange(18).reshape(2, 3, 3)
np.sum(c, axis=2)

array([[ 3, 12, 21],
       [30, 39, 48]])

In [4]:
d = np.arange(16).reshape(4, 4)
z1, z2 = np.split(d, 2, axis=1)
z1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])